apiVersion: v1
kind: Secret

metadata:
  name: customer360-secret

type: Opaque

stringData:
  API_KEY: "replace-with-production-api-key"
  DATABASE_URL: "postgresql+psycopg://customer360:replace-password@postgres-service:5432/customer360"