"""add outbox events table

Revision ID: 12c285050662
Revises: b8584a766c1f
Create Date: 2026-07-25 18:37:07.120139

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '12c285050662'
down_revision: str | Sequence[str] | None = 'b8584a766c1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
