"""add next retry timestamp

Revision ID: 1811e890ede7
Revises: f45862c54dbc
Create Date: 2026-07-25 19:04:55.977346

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1811e890ede7'
down_revision: str | Sequence[str] | None = 'f45862c54dbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
