"""add retry and dlq fields

Revision ID: f45862c54dbc
Revises: 12c285050662
Create Date: 2026-07-25 18:43:15.746199

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f45862c54dbc'
down_revision: str | Sequence[str] | None = '12c285050662'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
